"""create character sheet tables

Revision ID: 0cf90c763700
Revises: 5c0c2e7514f0
Create Date: 2024-09-03 10:25:11.852560

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = '0cf90c763700'
down_revision = '5c0c2e7514f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    if environment == "production":
        op.execute(f"ALTER TABLE games SET SCHEMA {SCHEMA};")

    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('character_name', sa.String(length=255), nullable=False),
    sa.Column('background', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )

    if environment == "production":
        op.execute(f"ALTER TABLE characters SET SCHEMA {SCHEMA};")

    op.create_table('character_armory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('armor_name', sa.String(length=255), nullable=True),
    sa.Column('armor_rating', sa.Integer(), nullable=True),
    sa.Column('traits', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )

    if environment == "production":
        op.execute(f"ALTER TABLE character_armory SET SCHEMA {SCHEMA};")

    op.create_table('character_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('skill_name', sa.String(length=255), nullable=False),
    sa.Column('skill_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )

    if environment == "production":
        op.execute(f"ALTER TABLE character_skills SET SCHEMA {SCHEMA};")

    op.create_table('character_weapons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('weapon_name', sa.String(length=255), nullable=True),
    sa.Column('dice_pool', sa.String(length=50), nullable=True),
    sa.Column('damage', sa.String(length=50), nullable=True),
    sa.Column('extra_damage', sa.String(length=50), nullable=True),
    sa.Column('armor_piercing', sa.Integer(), nullable=True),
    sa.Column('salvo', sa.Integer(), nullable=True),
    sa.Column('range', sa.String(length=50), nullable=True),
    sa.Column('traits', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )

    if environment == "production":
        op.execute(f"ALTER TABLE character_weapons SET SCHEMA {SCHEMA};")

    op.create_table('delta_green_characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('constitution', sa.Integer(), nullable=True),
    sa.Column('dexterity', sa.Integer(), nullable=True),
    sa.Column('intelligence', sa.Integer(), nullable=True),
    sa.Column('power', sa.Integer(), nullable=True),
    sa.Column('charisma', sa.Integer(), nullable=True),
    sa.Column('hit_points', sa.Integer(), nullable=True),
    sa.Column('willpower_points', sa.Integer(), nullable=True),
    sa.Column('sanity_points', sa.Integer(), nullable=True),
    sa.Column('breaking_point', sa.Integer(), nullable=True),
    sa.Column('distinguishing_features', sa.Text(), nullable=True),
    sa.Column('motivations_mental_disorders', sa.Text(), nullable=True),
    sa.Column('incidents_sanity_loss', sa.Text(), nullable=True),
    sa.Column('physical_description', sa.Text(), nullable=True),
    sa.Column('bonds', sa.Text(), nullable=True),
    sa.Column('wounds', sa.Text(), nullable=True),
    sa.Column('ailments', sa.Text(), nullable=True),
    sa.Column('personal_details_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )

    if environment == "production":
        op.execute(f"ALTER TABLE delta_green_characters SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delta_green_characters')
    op.drop_table('character_weapons')
    op.drop_table('character_skills')
    op.drop_table('character_armory')
    op.drop_table('characters')
    op.drop_table('games')
    # ### end Alembic commands ###
